version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "org.springframework.boot:*"
    versions: [">=4.0.0"]
  - dependency-name: "org.jooq:jooq"
    # Starting from 3.20, jooq requires Java 21. We're still targeting 17.
    versions: [">=3.20.0"]
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
